### ISSUE TITLE
`node_icons` property `draw` does nothing?

### ISSUE THREAD

**Issue by cskau** [enzet/map-machine#156]
I've been experimenting with modifying the `default.yml` scheme, and tried to add entries to the existing `group: "No draw"`, with an entry like this:
```yaml
  - group: "No draw"
    tags:
    - tags: {"addr:housenumber": "*"}
      draw: false
```

However, whenever I render tiles with the modified scheme, all matching nodes still seem to render, regardless of the value of `draw`.

To verify the nodes are matching as expected I have also tried:
```yaml
  - group: "No draw"
    tags:
    - tags: {"addr:housenumber": "*"}
      shapes: [stratovolcano]
```
Which does make the nodes render with the `stratovolcano` icon as expected.

FWIW, I had a quick look through the code, but could not see any place where `draw` was actually being used.
